### PR TITLE
Adding Symfony4 support

### PR DESCRIPTION
**Pull request by mwadon**
#SymfonyConHackday2017

### CODE REVIEW

**Comment by mwadon** [comment]
@egeloen can you take a look?

**Comment by Nyholm** [comment]
@egeloen excuse me if Im wrong. But this bundle is deprecated. This bundle is the predecessor of HTTPlug bundle. 

Maybe we should add a PR directing user to HTTPlug?

**Comment by egeloen** [comment]
@mwadon Thanks a lot for your contribution! Unfortunately, this bundle is totally deprecated. I know there is no information about that anywhere but it is its current state...

As @Nyholm explained, you should migrate to HTTPlug which is clearly much more feature rich and maintained.

Do you use this bundle directly or its a dependency of an other library you use?

**Comment by mwadon** [comment]
@egeloen No problem. I didn't know. I don't use this bundle. I was on HackDay after SymfonCon conference 2 weeks ago and we was updating bundles to support of Symfony 4. This bundle was on the list ;)

@Nyholm thanks for your help

**Pull request closed without merging**
